name: model_server

channels:
- conda-forge

dependencies:
- pip==20.1.1
- Flask==1.1.2
- numpy==1.18.4
- scikit-learn==0.23.1
- sentence-transformers==0.3.8
- numpy==1.18.4
- pandas==1.0.5
- torch==1.7.0
- xlrd==1.2.0
- nltk==3.5